export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS';
export const SINGLE_PRODUCT_FAIL = 'SINGLE_PRODUCT_FAIL';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_ERROR = 'CART_ERROR';
