export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS';
export const SINGLE_PRODUCT_FAIL = 'SINGLE_PRODUCT_FAIL';
